# ThreatClaw — Fluent Bit Parsers

[PARSER]
    Name            syslog-rfc3164
    Format          regex
    Regex           ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
    Time_Key        time
    Time_Format     %b %d %H:%M:%S

[PARSER]
    Name            syslog-rfc5424
    Format          regex
    Regex           ^\<(?<pri>[0-9]{1,5})\>1 (?<time>[^ ]+) (?<host>[^ ]+) (?<ident>[^ ]+) (?<pid>[^ ]+) (?<msgid>[^ ]+) (?<extradata>(\[(.*?)\]|-)+) (?<message>.+)$
    Time_Key        time
    Time_Format     %Y-%m-%dT%H:%M:%S.%L%z

[PARSER]
    Name            docker_json
    Format          json
    Time_Key        time
    Time_Format     %Y-%m-%dT%H:%M:%S.%L

[PARSER]
    Name            json
    Format          json

[PARSER]
    Name            auth_pam
    Format          regex
    Regex           ^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<module>[^\[]*)\[(?<pid>[0-9]+)\]: (?<message>.*)$
    Time_Key        time
    Time_Format     %b %d %H:%M:%S
