# ThreatClaw — Fluent Bit Parsers

[PARSER]
    Name            syslog-rfc3164
    Format          regex
    Regex           ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
    Time_Key        time
    Time_Format     %b %d %H:%M:%S

[PARSER]
    Name            syslog-rfc5424
    Format          regex
    Regex           ^\<(?<pri>[0-9]{1,5})\>1 (?<time>[^ ]+) (?<host>[^ ]+) (?<ident>[^ ]+) (?<pid>[^ ]+) (?<msgid>[^ ]+) (?<extradata>(\[(.*?)\]|-)+) (?<message>.+)$
    Time_Key        time
    Time_Format     %Y-%m-%dT%H:%M:%S.%L%z

[PARSER]
    Name            docker_json
    Format          json
    Time_Key        time
    Time_Format     %Y-%m-%dT%H:%M:%S.%L

[PARSER]
    Name            json
    Format          json

[PARSER]
    Name            auth_pam
    Format          regex
    Regex           ^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<module>[^\[]*)\[(?<pid>[0-9]+)\]: (?<message>.*)$
    Time_Key        time
    Time_Format     %b %d %H:%M:%S

# pfSense filterlog format
[PARSER]
    Name            pfsense
    Format          regex
    Regex           ^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) filterlog\[(?<pid>[0-9]+)\]: (?<rule_number>[^,]*),(?<sub_rule>[^,]*),(?<anchor>[^,]*),(?<tracker>[^,]*),(?<interface>[^,]*),(?<reason>[^,]*),(?<action>[^,]*),(?<direction>[^,]*),(?<ip_version>[^,]*),(?<message>.*)$
    Time_Key        time
    Time_Format     %b %d %H:%M:%S

# FortiGate syslog format (key=value)
[PARSER]
    Name            fortigate
    Format          regex
    Regex           ^(?<time>[^ ]+ [^ ]+) (?<host>[^ ]+) (?<message>.*)$
    Time_Key        time
    Time_Format     %Y-%m-%d %H:%M:%S

# Windows NXLog syslog format
[PARSER]
    Name            nxlog_windows
    Format          regex
    Regex           ^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<source>[^ ]*) (?<message>.*)$
    Time_Key        time
    Time_Format     %b %d %H:%M:%S
